### ISSUE TITLE
s3 store support broken?

### ISSUE THREAD

**Issue by implr** [trofi/nix-guix-gentoo#12]
Despite nix being emerged with `USE=etc-profile gc s3 sodium`, attempting to access a s3 based store fails, eg.:
```
$ nix ping-store --store 's3://BUCKET'
error: don't know how to open Nix store 's3://BUCKET'
```
This seems to be a problem with the ebuild - nix from `nix-shell -p nix` does work - but that doesn't fix s3 being broken in nix-daemon.

**Comment by trofi** [comment]
I'm notvery familiar with `s3` backend, but I suspect ./configure did not detect a library for you. Can you attach your nix's `build.log` so we could check what was discovered?

**Comment by trofi** [comment]
With the patch above it seems to work for me:
```
$ nix ping-store --store 's3://BUCKET'
error: AWS error fetching 'nix-cache-info': The specified bucket does not exist
```

**Comment by implr** [comment]
Unfortunately doesn't seem to work still, configure says
`checking for aws/s3/S3Client.h... no`
full log here: https://gist.github.com/implr/3c990998a883f1f71ae3f17a7889a7f7

**Comment by implr** [comment]
Ah, wait, I have dev-libs/aws-sdk-cpp installed with USE=-s3 (seems to be the default). Will recompile and try again.

**Comment by trofi** [comment]
I don't have `USE=s3` either. Can you also upload your `config.log`? I wonder why header did not work for you as is.

We'll also need to turn this failure into a configure failure instead of silent feature removal.

**Comment by implr** [comment]
That header did not exist on my system with `USE=-s3` at all. It did get installed with aws-sdk-cpp with +s3, and after recompiling nix s3 does work now. Now I wonder why it worked for you, or where did you get the header from on your system, heh

**Comment by trofi** [comment]
Oh, now I see the failure as well /o\. It's because I installed dev-libs/aws-sdk-cpp[s3] initially as a one-off run of 'USE=s3 emerge -v1 nix' and it pulled a header for me. But not I updated the @world.

**Comment by trofi** [comment]
Should be fixed now.
