### ISSUE TITLE
Merge Failure: sys-apps/nix-2.6.0

### ISSUE THREAD

**Issue by m0lese** [trofi/nix-guix-gentoo#15]
Build log: https://hardbin.com/ipfs/QmXQc8hb4f5TJ2znhGtyDrt9agHyKvgQimqwnvKEtoBtaK/#9HNocqrEdXfHzHy62KHofznfJN2azmkStL9zGpetPe27

**Comment by trofi** [comment]
```
...
(.data.rel.ro._ZTVN3nix14UDSRemoteStoreE[_ZTVN3nix14UDSRemoteStoreE]+0x138): undefined reference to `nix::Config::toKeyValue[abi:cxx11]()'
collect2: error: ld returned 1 exit status
make: *** [mk/lib.mk:117: /var/tmp/portage/sys-apps/nix-2.6.0/image/usr/lib64/libnixstore.so] Error 1
```

Ah, that's a link failure when previous version of `nix` is present in system: 

Worked around by restoring the patch we applied in `2.3`: https://github.com/trofi/nix-guix-gentoo/commit/f93e7c117f4a565478e50d427f51629dbb9e19fa. Will attempt to upstream again.

**Comment by trofi** [comment]
Should work now.

**Comment by m0lese** [comment]
Oh, nice. That was pretty quick.

**Comment by trofi** [comment]
Proposed fix upstream as https://github.com/NixOS/nix/pull/6060
