### ISSUE TITLE
Reason for move to overlay?

### ISSUE THREAD

**Issue by JanBessai** [trofi/nix-guix-gentoo#2]
Hey,

first of all thanks! I love being able to run Nix on Gentoo, because it gives me a fast way to install and run and one-off test garbage programs as a user without messing up my system. The [blog post](https://trofi.github.io/posts/196-nix-on-gentoo-howto.html) on it also has been very helpful.

During a recent update portage notified me that nix is going to move into this overlay
```
# Sergei Trofimovich <slyfox@gentoo.org> (2019-11-25)
# Mask for removal from main tree into ::nix-guix overlay.
# Removal in 30 days.
```

I am fine with having the overlay, but I was just wondering: is there any reason why things don't remain in the main tree? Couldn't find an answer on bugzilla or elsewhere, so I'm trying here.

-- Jan

PS.: Not sure if the overlay can do it, but linking to the blog post in a readme for the overlay would be nice for fresh users.

**Comment by trofi** [comment]
Thank you for the kind words! It's always nice to see when package helps someone.

> is there any reason why things don't remain in the main tree?

I personally am totally fine with `nix` being in the `::gentoo` and think it's a great example of challenging package.

Members of Gentoo QA team including Gentoo GA team lead oppose to have such a package in the main tree:
- https://archives.gentoo.org/gentoo-dev/message/e6b3f0c3a04b7fa92ada1fedd2b7018c
- https://archives.gentoo.org/gentoo-dev/message/91d0d4ee007ee82c476bcd945df7a364

Given that hostility is quite irrational I don't plan to perform a crusade for now. When the team rotates maybe I'll try again :)

There is a plan to remove current API that creates users in the ebuild without a reasonable substitute. I'll need to add workarounds for that that will not fit for `::gentoo`.

> Not sure if the overlay can do it, but linking to the blog post in a readme for the overlay would be nice for fresh users.

I think it's a good idea! Inlining starter's guide into the repository's `README.md` should be slightly mode discoverable and maintainable approach. We could even document a few neat tricks.

**Comment by mschilli87** [comment]
Well, at least 5 out of 3 those users have already starred this repo. :wink:
I understand the reluctancy to reserve that many IDs but I find it a pity this resulted in the removal of guix from the tree. I use guix to build containers I use on non-gentoo non-guix systems I don't have root access to and I'm considering setting up another distro as my main driver after almost 10 years of Gentoo because of that. So thank you for keeping up the work regardless. If you need any support in the future, feel free to ping me (not that my voice matters).

**Comment by trofi** [comment]
Meanwhile I lost `::gentoo` access and will unlikely to get ebuilds back to `::gentoo`. Closing.
