### ISSUE TITLE
sys-apps/busybox-nix-sandbox-shell-1.35.0 emake failed

### ISSUE THREAD

**Issue by brothermechanic** [trofi/nix-guix-gentoo#22]
build log http://dpaste.com/BQ4XP8LLY
short log
```
Console input/output is redirected. Run 'make oldconfig' to update configuration.

make[2]: *** [/var/tmp/portage/sys-apps/busybox-nix-sandbox-shell-1.35.0/work/busybox-1.35.0/scripts/kconfig/Makefile:40: silentoldconfig] Error 1
make[1]: *** [/var/tmp/portage/sys-apps/busybox-nix-sandbox-shell-1.35.0/work/busybox-1.35.0/Makefile:444: silentoldconfig] Error 2
make: *** [Makefile:522: include/autoconf.h] Error 2
```

**Comment by brothermechanic** [comment]
wgetpaste /var/tmp/portage/sys-apps/busybox-nix-sandbox-shell-1.35.0/work/busybox-1.35.0/.config
http://dpaste.com/CBWMEE9FG

**Comment by trofi** [comment]
Thank you! The snippet:

```
CONFIG_EXTRA_CFLAGS="-march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512er -mno-avx512pf -mno-avx512vbmi -mno-avx512ifma -mno-avx5124vnniw -mno-avx5124fmaps -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mno-hle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mno-prefetchwt1 -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mno-rtm -mno-serialize -msgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=skylake -dumpbase null -O2 -pipe"
CONFIG_EXTRA_LDFLAGS="-Wl,-O1 -Wl,--as-needed"
```

Looks like it's just string length (about 1.2KB). Should be easy to increase the buffer size. Looking.

**Comment by trofi** [comment]
Pushed https://github.com/trofi/nix-guix-gentoo/commit/ea0d94a559cd69afcba0a4a5e226f20ced7f5e88 to increase line length from 1K to 64K. That should fix it for you. At least it did for me when I used your `CFLAGS`.

**Comment by trofi** [comment]
I must say your CFLAGS are unusually long. All(?) the `-mno-` flags look redundant against already passed in -`march=skylake`.

I usually use the following hack to get minimum amount of flags needed to be changed on top of `-march=` value you already pass: https://wiki.gentoo.org/wiki/Gcc-ICE-reporting-guide#Expand_-march.3Dnative.2C_exact_gcc_version_and_other_system-specific_options.

Chances are you will not need to specify that many overrides.

**Comment by brothermechanic** [comment]
Cool!
Now works with all my cflags!
Thank you)

**Comment by trofi** [comment]
Interestingly upstream kbuild (in `linux.git`) fixed the bug in 2012: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1a7a8c6fd8ca24d3692dacddf8d658c9bb9c14ad. `busybox` needs to sync this change in some form. Filed https://bugs.busybox.net/show_bug.cgi?id=15031 to fix `busybox` properly upstream.
