### ISSUE TITLE
sys-apps/nix: user CXXFLAGS are not respected

### ISSUE THREAD

**Issue by 0n-s** [trofi/nix-guix-gentoo#26]
`sys-apps/nix` (tested: 2.12.0) builds without any of the user's CXXFLAGS as specified in `/etc/portage/make.conf`.

Rather funny because the ebuild's removal of the package's implicit optimization CXXFLAGS results in the package being built without any optimizations because of this bug. Definitely not the worst package that could be hit by this issue, but it's nonetheless amusing.

**Comment by trofi** [comment]
Can you post your `build.log` and `emerge --info`? I wonder if it's obvious from the log why flags do not apply.

**Comment by trofi** [comment]
Reproduced locally. Probably came back with https://github.com/NixOS/nix/commit/f5b7991e59d8c9ae38fb4c9074a5847942caab73 revert.

**Comment by trofi** [comment]
Give https://github.com/trofi/nix-guix-gentoo/commit/099fc5424337306e2ad84a75c9d35dd21b15128f a try. In a light build test it does seem to do the right thing.

**Comment by 0n-s** [comment]
Yup, does the job. Thanks!

**Comment by trofi** [comment]
Proposed the fix upstream as https://github.com/NixOS/nix/pull/7476
