### ISSUE TITLE
The GDK_PIXBUF_MODULE_FILE environment variable fix doesn't seem to be necessary anymore

### ISSUE THREAD

**Issue by gagero** [trofi/nix-guix-gentoo#27]
The bug was closed with a patch merged yesterday.

**Comment by trofi** [comment]
Good point!

Yeah, removing it sounds reasonable. Probably worth rephrasing `README.md` to still mention now to filter out leaked variables in general and past bug as an example to handle it.

**Comment by trofi** [comment]
How about this update (just pushed): https://github.com/trofi/nix-guix-gentoo/commit/1c229256c5b82cb1025ab23010efcb235e231466
