### ISSUE TITLE
Permissions errors with nix-build

### ISSUE THREAD

**Issue by Gooberpatrol66** [trofi/nix-guix-gentoo#34]
I'm having issues with this command, which is required to build robotnix:

```
nix-build --option extra-sandbox-paths /keys="/home/nathan/guix-configs/robotnix/keys" --arg configuration ~/guix-configs/robotnix/crosshatch.nix -A ota 
these 2 derivations will be built:
  /nix/store/vd325v1dk21w4v53kkvlai88ag7s7rk9-crosshatch-signed_target_files-2022041111.zip.drv
  /nix/store/jhmczwpjhhzwdxfra7fvssqfkiqqdjpx-crosshatch-ota_update-2022041111.zip.drv
building '/nix/store/vd325v1dk21w4v53kkvlai88ag7s7rk9-crosshatch-signed_target_files-2022041111.zip.drv'...
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/chromium.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/chromiumwebview.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/com.android.connectivity.resources.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/com.android.hotspot2.osulogin.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/com.android.wifi.resources.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/releasekey.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/platform.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/shared.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/media.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/networkstack.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/crosshatch/avb.pem: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/releasekey.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/platform.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/shared.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/media.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/networkstack.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/dre/avb.pem: Permission denied
cp: /dev/shm/robotnix_keys.XXXX6Yz8CB/f-droid.pk8: Permission denied
```
The files in robotnix/keys are owned by nathan:nathan, and nathan is in the nixbld group. /etc/nix/nix.conf contains "trusted-users = nathan". I set sysctl fs.protected_regular=0 because I heard that could be a problem. Any idea what the issue is?

**Comment by trofi** [comment]
> nathan is in the nixbld group

That is a bit scary setup. AFAUI `nix-daemon` pick first free user in `nixbld` group to build the package. Sometimes it will be `nathan`, but sometimes it will be one of `nixbld*` ones. You can't predict which one. I would suggest just remove your real user from `nixbld`.

`trusted-users =` allows you to run more privileged commands against `nix-daemon` (like copying trusted derivations into local store). Builting derivations locally does not require `trusted-users`. `nix-daemon` still runs as root itself and spawns builders as `nixbld*` users. It's probably unimportant here.

It feels like `cp` is called from within a built derivation (and not during copy if the inputs into the store). If that is corret then presence of `/dev/shm` within build environment is a bit surprising.

Try adding `--verbose` (and maybe `--debug`) option to `nix-build` command to have more details and to see if it's a client (running as your user) or a server (runnig as `root/nixbld`) who tries to do the copying.

**Comment by Gooberpatrol66** [comment]
`That is a bit scary setup. AFAUI nix-daemon pick first free user in nixbld group to build the package. Sometimes it will be nathan, but sometimes it will be one of nixbld* ones. You can't predict which one. I would suggest just remove your real user from nixbld.`
This gave me the idea to chown the keys to nixbld1:nixbld, and that caused the build to work. The keys merely being owned by the nixbld group didn't work, they have to be owned by the specific nixbld* user nix chooses. Is there a way to fix this?

Try adding --verbose (and maybe --debug) option to nix-build command to have more details and to see if it's a client (running as your user) or a server (runnig as root/nixbld) who tries to do the copying.
Here's the log for reference: 
[log.txt](https://github.com/trofi/nix-guix-gentoo/files/11367885/log.txt)

**Comment by trofi** [comment]
Very interesting. Normally I would expect inputs to be copied to `/nix/store/` first. But it seems that here keys are expected to be passed to the build sandbox by allowing it via `extra-sandbox-paths` by way of `crosshatch.nix` definition:

```
...
sandbox setup: bind mounting '/home/nathan/guix-configs/robotnix/keys' to '/nix/store/vd325v1dk21w4v53kkvlai88ag7s7rk9-crosshatch-signed_target_files-2022041111.zip.drv.chroot/keys'
...
building '/nix/store/vd325v1dk21w4v53kkvlai88ag7s7rk9-crosshatch-signed_target_files-2022041111.zip.drv'...
cp: /dev/shm/robotnix_keys.XXXXYzAwjG/chromium.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXXYzAwjG/chromiumwebview.pk8: Permission denied
cp: /dev/shm/robotnix_keys.XXXXYzAwjG/com.android.connectivity.resources.pk8: Permission denied
```

I wonder why does it need a bind. Perhaps to avoid storing private keys as a world-readable `nix/store/` path? Should not be very important.

Do you know why `/dev/shm` comes from here? Could it be that `/home/nathan/guix-configs/robotnix/keys` is a symlink to `/dev/shm`? Or `~/guix-configs/robotnix/crosshatch.nix` already somehow has it embedded? Or an environment variable? You might want to pass that through `/dev/shm` as well (if it's intended to be a part of `/home/nathan/guix-configs/robotnix/keys` resolution).

**Comment by Gooberpatrol66** [comment]
Fixed with chmod g+rw -R on the keys directory. Thank you for the help!
