### ISSUE TITLE
rapidcheck build error

### ISSUE THREAD

**Issue by FyrN22** [trofi/nix-guix-gentoo#35]
[info.txt](https://github.com/trofi/nix-guix-gentoo/files/11412702/info.txt)
[log.txt](https://github.com/trofi/nix-guix-gentoo/files/11412704/log.txt)

**Comment by trofi** [comment]
Yeah, it's a `gcc-13` incompatibility:

```
/var/tmp/portage/dev-cpp/rapidcheck-0_pre20230113/work/rapidcheck-0_pre20230113/include/rapidcheck/detail/Utility.h:6:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    5 | #include <limits>
  +++ |+#include <cstdint>
    6 |
```


I pushed `rapidcheck-0_pre20230416` yesterday as https://github.com/trofi/nix-guix-gentoo/commit/64edf8fe00c3fb3bcfc53aeb9287a4d3fb7cc882. If you sync the overlay updates does it work for you?

**Comment by FyrN22** [comment]
I synced the overlay, and now it fails to emerge dev-cpp/rapidcheck:

ebuild.sh, line  136:  Called src_compile
 *   environment, line 2059:  Called cmake_src_compile
 *   environment, line  826:  Called cmake_build
 *   environment, line  795:  Called eninja
 *   environment, line 1250:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"

**Comment by trofi** [comment]
Can you post full log output? Looks like it's missing the actual error message and only prints the backtrace of error printer itself.

**Comment by FyrN22** [comment]
[log.txt](https://github.com/trofi/nix-guix-gentoo/files/11413211/log.txt)

**Comment by trofi** [comment]
It is still trying to install an old version for you:

```
/var/tmp/portage/dev-cpp/rapidcheck-0_pre20230113/work/rapidcheck-0_pre20230113/include/rapidcheck/detail/Utility.h:6:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    5 | #include <limits>
  +++ |+#include <cstdint>
    6 |
```

Double-check if your overlay checkout has up-to-date file versions that match https://github.com/trofi/nix-guix-gentoo/tree/master/dev-cpp/rapidcheck

**Comment by FyrN22** [comment]
i have rapidcheck-0_pre20230113.ebuild, but not rapidcheck-0_pre20230416.ebuild, should i just add it to /var/db/repos/nix-guix/dev-cpp/rapidcheck/ ?

**Comment by trofi** [comment]
No, normally you would sync the overlay with `emerge --sync` to pull the updates (depending on how you installed it). That should copy all files automatically.

**Comment by FyrN22** [comment]
i did emerge --sync, and this repo returned with the code = 0

**Comment by trofi** [comment]
Did it update the files? If not try to add an entry in `/etc/portage/repos.conf` like https://github.com/trofi/nix-guix-gentoo/#enabling-the-overlay specifies. That should be enough for `emerge --sync` to work.

**Comment by FyrN22** [comment]
i added that already to the repos.conf, i also tired the eselect-repository, but still fails the build on rapidcheck

**Comment by trofi** [comment]
If you do `# emaint sync -r nix-guix` what is the full output?

**Comment by FyrN22** [comment]
emaint sync -r nix-guix
>>> Syncing repository 'nix-guix' into '/var/db/repos/nix-guix'...
/usr/bin/git fetch origin --depth 1
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
/usr/bin/git reset --merge refs/remotes/origin/master
=== Sync completed for nix-guix

 * IMPORTANT: 40 config files in '/etc' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.

 * IMPORTANT: 18 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


Action: sync for repo: nix-guix, returned code = 0

**Comment by trofi** [comment]
Looks good. How about `$ cd /var/db/repos/nix-guix && git log`?

**Comment by FyrN22** [comment]
commit d00abbc44841e876d5db47e60ad408cb1d1c322b (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Repository mirror & CI <repomirrorci@gentoo.org>
Date:   Mon Apr 24 22:19:03 2023 +0000

**Comment by trofi** [comment]
Aha, you are using the `gentoo`'s stale mirror. Double-check your `repos.conf` for a git repository path to point at https://github.com/trofi/nix-guix-gentoo.git

**Comment by FyrN22** [comment]
i have the nix-guix.conf inside the repos.conf.

**Comment by trofi** [comment]
Can you post it's full content here?

**Comment by FyrN22** [comment]
[eselect-repo.txt](https://github.com/trofi/nix-guix-gentoo/files/11413530/eselect-repo.txt)
[gentoo.txt](https://github.com/trofi/nix-guix-gentoo/files/11413531/gentoo.txt)
[nix-guix.txt](https://github.com/trofi/nix-guix-gentoo/files/11413532/nix-guix.txt)

**Comment by trofi** [comment]
Hm, that looks correct. Though your `emerge --info` from the first comment contains the other repo link:

```
nix-guix
    location: /var/db/repos/nix-guix
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/nix-guix.git
    masters: gentoo
    volatile: False
```

Does your `emerge --info` still refer `https://github.com/gentoo-mirror/nix-guix.git`?

**Comment by FyrN22** [comment]
i switched it to the right repo link

**Comment by trofi** [comment]
Aha. I did not quite get after which comment you have fixed the link: before or after you tried to sync.

Does `emerge --sync` pull from the correct repository now?

**Comment by FyrN22** [comment]
No, its still the old one.

**Comment by trofi** [comment]
Aha. I wonder if `emerge --sync` does not update git repository paths after it was checked out once. What path do you see in `cat /var/db/repos/nix-guix/.git/config`?

If it's a stale on try to nuke it and refetch:

```
# rm -rfv /var/db/repos/nix-guix && emerge --sync
```

**Comment by trofi** [comment]
Meanwhile I filed https://bugs.gentoo.org/905869 to consider fixing `emerge --sync`'s behavior to update git repository link.

**Comment by FyrN22** [comment]
it was the stale, but now rapid build works but nix fails the build
[nixlog.txt](https://github.com/trofi/nix-guix-gentoo/files/11414803/nixlog.txt)

**Comment by trofi** [comment]
Yay, progress! 

```
make: *** No rule to make target '/usr/bin/nix', needed by 'doc/manual/src/command-ref/new-cli'.  Stop.
make: *** Waiting for unfinished jobs....
```

I think it's a deficiency in DESTDIR patch. I'll try to reproduce it by uninstalling `nix` locally. I think it happens to work for me only because I had older version around.

**Comment by trofi** [comment]
Reproduced locally and pushed possible fix: https://github.com/trofi/nix-guix-gentoo/commit/35e42f68df621842c7cba5914dbfe1ed448bf2cd . Please try to sync the repo again and give it a try.

**Comment by FyrN22** [comment]
It works now, thanks for helping!

**Comment by trofi** [comment]
Thank you for the report!
