### ISSUE TITLE
gnutls-3.8.0 no longer includes guile USE flag.

### ISSUE THREAD

**Issue by jaccarmac** [trofi/nix-guix-gentoo#40]
I noticed this minor error trying to upgrade.

```
WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

net-libs/gnutls:0

  (net-libs/gnutls-3.8.0:0/30.30::gentoo, ebuild scheduled for merge) USE="cxx idn nls openssl seccomp tls-heartbeat zlib -brotli -dane -doc -examples -pkcs11 (-sslv2) (-sslv3) -static-libs -test (-test-full) -tools -verify-sig -zstd" ABI_X86="32 (64) (-x32)" conflicts with
    net-libs/gnutls[guile] required by (sys-apps/guix-1.4.0-r2:0/0::nix-guix, installed) USE="userland_GNU" ABI_X86="(64)"
                    ^^^^^
```

It appears that while the `guile` flag appears in [3.7.8](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/gnutls/gnutls-3.7.8.ebuild?id=00a87ff8cb08b23e282582253537974a60ae9dd2) and [3.7.9](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/gnutls/gnutls-3.7.9.ebuild?id=00a87ff8cb08b23e282582253537974a60ae9dd2), it disappeared in the [3.8.0](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/gnutls/gnutls-3.8.0.ebuild?id=00a87ff8cb08b23e282582253537974a60ae9dd2) ebuild.

I'm unable to find further information about why, and haven't debugged the Guix ebuild here with 3.8.0. Is this a known issue, something changing in `net-libs/gnutls`, or something that needs to be changed in this repository?

**Comment by trofi** [comment]
It should have been fixed a few months ago with https://github.com/trofi/nix-guix-gentoo/commit/65a1c535384f53388d0c0adf82ecd00722b2e508

Can you check if your local copies of the ebuilds contain the change?

**Comment by trofi** [comment]
Also if your ebuilds are up to date make sure `dev-scheme/guile-gnutls` is keyworded. `||` dependencies are a bit tricky to resolve automatically. `emerge` might take the wrong branch and give suboptimal suggestions.

**Comment by jaccarmac** [comment]
I have the correct `RDEPEND`, so it must be

> `||` dependencies are a bit tricky to resolve automatically.

Thanks for the pointer!

**Comment by trofi** [comment]
Sometimes also passing huge `--backtrack=9999` can get past blockers as well. What did you do in the end? :)

**Comment by jaccarmac** [comment]
Added `dev-scheme/guile-gnutls ~amd64` to my Guix `accept_keywords`.

I'll try `backtrack` next time I run into a similar issue; I have only added that flag in the past when prompted by Portage.

**Comment by xgqt** [comment]
I recommend adding `dev-scheme/guile*` to unmask all the guile stuff as I think most if not all of it is unstable.
