### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by viniciorl** [trofi/nix-guix-gentoo#42]
I just started an upgrade on my Gentoo system and noticed the nix package from this repository was failing to build.

After looking at the output on the terminal, it seemed it was failing a check for "libgit2".

Figuring the issue was a missing dependency, I manually installed "dev-libs/libgit2" to see if that would fix the problem, and it did.
Obviously that is a hacky solution, and I was wondering if this dependency could be added to the ebuild on this repository instead of having to rely on this temporary fix.

Thank you.

**Comment by trofi** [comment]
Good point!

`libgit2` dependency was added in https://github.com/NixOS/nix/commit/cf59ea83ec98522113bf2fd81678537a871d0339 which is part of `nix-2.20` and later. I'll try to add it.

**Comment by trofi** [comment]
Pushed the possible fix as https://github.com/trofi/nix-guix-gentoo/commit/7a088f3dba86631514e83529fcd9db0c24c2deb1

Thank you!
