### ISSUE TITLE
sys-devel/autoconf-archive was moved to dev-build/autoconf-archive

### ISSUE THREAD

**Issue by faithanalog** [trofi/nix-guix-gentoo#43]
see `gentoo/profiles/updates/1Q-2024`

the main nix.ebuild depends on this. I don't know if it matters to change this in the ebuild, nor whether that move requires an `-r1` sort of update to the .ebuild filename, else I would PR something. Mostly I am opening this issue to learn whether it should be changed, and also let you know that it happened.

i noticed this because my binhost has the package on both the old and new atoms and so for some reason my system is trying to install it twice from both atoms lol

**Comment by faithanalog** [comment]
im realizing that i think nix-guix-gentoo is not installed on my system with the git mirror

```
commit d00abbc44841e876d5db47e60ad408cb1d1c322b (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Repository mirror & CI <repomirrorci@gentoo.org>
Date:   Mon Apr 24 22:19:03 2023 +0000

    Merge updates from master
```

and maybe i have bigger problems

**Comment by faithanalog** [comment]
yeah this was my actual problem. i was still on nix 2.15 too -.-

**Comment by trofi** [comment]
Yeah, the package move was done in the overlay in bf4f21fc37b6449a228f03d7b31dd55ec24cffc4 (about a month ago).

The procedure to enable an overlay was changed a while ago. Can you check if the overlay points to this repo and not a stale gentoo mirror?

https://github.com/trofi/nix-guix-gentoo/?tab=readme-ov-file#enabling-the-overlay describes how exactly the entry should look like.

**Comment by faithanalog** [comment]
yeah the overlay was pointing at https://github.com/gentoo-mirror/nix-guix but I've fixed it up now
