### ISSUE TITLE
no sys-devel/autoconf-archive

### ISSUE THREAD

**Issue by Gooberpatrol66** [trofi/nix-guix-gentoo#44]
```
!!! The following update has been skipped due to unsatisfied dependencies:

sys-apps/nix:0

  selected: (sys-apps/nix-2.16.1:0/0::nix-guix, installed)
  skipped: (sys-apps/nix-2.16.1:0/0::nix-guix, ebuild scheduled for merge) (see unsatisfied dependency below)

emerge: there are no ebuilds to satisfy "sys-devel/autoconf-archive".
(dependency required by "sys-apps/nix-2.16.1::nix-guix" [ebuild])

```

**Comment by trofi** [comment]
`2.16.1` was released quite a while ago. The overlay has `2.20.3` and later: https://github.com/trofi/nix-guix-gentoo/tree/master/sys-apps/nix

Can you check which `git` repository you are syncing from? Make sure it's not a stale link to the gentoo mirror. https://github.com/trofi/nix-guix-gentoo?tab=readme-ov-file#enabling-the-overlay shows expected file contents.

**Comment by Gooberpatrol66** [comment]
Sorry, my eix-sync was broken.
