### ISSUE TITLE
Hasktorch?

### ISSUE THREAD

**Issue by LemonBreezes** [trofi/nix-guix-gentoo#46]
Hello. Would someone please package Hasktorch and add it to this repository? Doing ML in Haskell is really awesome.

**Comment by trofi** [comment]
`::nix-guix` overlay tries to keep the scope of the overlay just to `sys-apps/nix` and `sys-apps/guix` (and their dependencies missing/broken in `::gentoo`).

Perhaps `::haskell` might be a better overlay for that? Or an ML-related overlay if such a thing exist

**Comment by LemonBreezes** [comment]
> `::nix-guix` overlay tries to keep the scope of the overlay just to `sys-apps/nix` and `sys-apps/guix` (and their dependencies missing/broken in `::gentoo`).
> 
> Perhaps `::haskell` might be a better overlay for that? Or an ML-related overlay if such a thing exist

Yes, I accidentally opened this in the wrong repository. I had both this repository and Gentoo Haskell opened on separate tabs and forgot which one I was on.
