### ISSUE TITLE
Would you like to move it to Guru? (and discussion about overlays and ::gentoo)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [trofi/nix-guix-gentoo#48]
Official overlay.

So you will get manual and automatic checks, more people will install it.

**Comment by trofi** [comment]
There are a few technical and social obstacles and inconveniences to that.

# technical

AFAIK `::nix-guix` by necessity violates some of `GURU`s requirements, like this one from [GURU#regulations](https://wiki.gentoo.org/wiki/Project:GURU#The_regulations):

> The primary purpose of GURU is to maintain packages not present in the Gentoo repository. Forking (overriding) actively maintained Gentoo packages into GURU is prohibited. If the package is moved to Gentoo, it should be removed from GURU.

For example for overridden packages today these are:
- `app-text/lowdown-nix` (fork of `app-text/lowdown`)
- `sys-apps/busybox-nix-sandbox-shell` (fork of `sys-apps/busybox`)

Sometimes I have to workaround other `::gentoo` breakages to get `nix` or `guix` installable at all. Recent examples are
- [boehm-gc](https://bugs.gentoo.org/923624)
- [guile](https://bugs.gentoo.org/905898)
- [lowdown](https://bugs.gentoo.org/811111), [again](https://bugs.gentoo.org/832590), [and again](https://bugs.gentoo.org/832797).

I suspect there are other policies that are explicitly violated by `::nix-guix` and are not welcome in `GURU`. For example I could not reach the conclusion of `app-user/*` package policy requirements when it was in `::gentoo`. Latest thread is at https://www.mail-archive.com/gentoo-dev@lists.gentoo.org/msg87263.html

# social

There is a general animosity towards `nix` being mentioned at all to some of the Gentoo devs. That proved to get hard to overcome. An example in addition to `app-user/*` example above is `/nix` and `/gnu` top-level directory exceptions. Those were just removed after a package was moved to overlay: https://github.com/gentoo/gentoo/commit/48735f318b6509fe5bc80f9b5d2a298f9cef5d73 . The exceptions were added in https://bugs.gentoo.org/670902 . From what I understand there is no way to silence the QA report.

I'm not using Gentoo on a daily basis, thus I can't really claim that I maintain these packages enough to be included in GURU.

As https://github.com/gentoo/api-gentoo-org/pull/532 shows being able to contribute to GURU or even have the overlay listed in `repositories.xml` apparently requires having very specific terms with Gentoo devs. I delisted my overlays in https://github.com/gentoo/api-gentoo-org/pull/600 to avoid these gray areas.

And my contributions are not welcome in Gentoo. Thus I have to minimize the amount of interactions to only minimal bug reporting.

**Comment by xgqt** [comment]
@vitaly-zdanevich 

> So you will get manual and automatic checks

This is not a problem. We can use CI software in this repo too.

---

@trofi 

> Sometimes I have to workaround other ::gentoo breakages to get nix or guix installable at all. Recent examples are
> ...
> guile
> ...

And we did work together on solving guile-related issues, haven't we? I see our relations on this matter in a good shape.

> As gentoo/api-gentoo-org#532 shows being able to contribute to GURU or even have the overlay listed in repositories.xml apparently requires having very specific terms with Gentoo devs.

That's ComRel thing here. If somebody GNOME contributor got banned by GNOME they would also take similar measures.

I used to be anti-this but I think I would agree that if somebody gets banned their access to community collection-type projects be also limited.

Whether Poly-C's "trial" was just I leave up to the reader. I do not remember what has happened there. 

> And my contributions are not welcome in Gentoo. 

What makes you say that?

---

IMO nix stuff should not go into ::guru but be available via eselect-repo so install is easier for eand-users.

**Comment by trofi** [comment]
> > Sometimes I have to workaround other ::gentoo breakages to get nix or guix installable at all. Recent examples are
> > ...
> > guile
> > ...
> 
> And we did work together on solving guile-related issues, haven't we? I see our relations on this matter in a good shape.

No complains from me here.

> > As [gentoo/api-gentoo-org#532](https://github.com/gentoo/api-gentoo-org/pull/532) shows being able to contribute to GURU or even have the overlay listed in repositories.xml apparently requires having very specific terms with Gentoo devs.
> 
> That's ComRel thing here. If somebody GNOME contributor got banned by GNOME they would also take similar measures.
> 
> I used to be anti-this but I think I would agree that if somebody gets banned their access to community collection-type projects be also limited.
> 
> Whether Poly-C's "trial" was just I leave up to the reader. I do not remember what has happened there.

I clearly violate some of the stated reasons for removal, like a broad interpretation of the meaning of "The owner has stopped using Gentoo." or meaning of slander. I would prefer not to be dependent too much on the "ComRel thing" towards me.

**Comment by xgqt** [comment]
@trofi 

I think this can be closed.
