### ISSUE TITLE
build error, patch fails to apply

### ISSUE THREAD

**Issue by scyleaf** [trofi/nix-guix-gentoo#49]
[info.txt](https://github.com/user-attachments/files/16512554/info.txt)
[build.log](https://github.com/user-attachments/files/16512555/build.log)
[environment.txt](https://github.com/user-attachments/files/16512556/environment.txt)

I wanted to try out guix but I can't get it to build because the patch fails.

**Comment by trofi** [comment]
Thank you for the report! The failure is in `guix-9999` version:

```
 * Applying guix-1.4.0_rc2-default-daemon.patch ...
patching file etc/guix-daemon.conf.in
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file etc/guix-daemon.conf.in.rej
patching file etc/guix-daemon.service.in
Hunk #1 succeeded at 9 (offset 3 lines).
patching file etc/guix-publish.conf.in
Hunk #1 succeeded at 12 (offset 3 lines).
patching file etc/guix-publish.service.in
Hunk #1 succeeded at 12 (offset 6 lines).
patching file nix/local.mk
Hunk #1 succeeded at 190 with fuzz 1.
Hunk #2 FAILED at 201.
1 out of 2 hunks FAILED -- saving rejects to file nix/local.mk.rej                        
```

Need to refresh a patch. Should take a few minutes. Meanwhile `guix-1.4.0-r4` might work for you as is.

**Comment by trofi** [comment]
Pushed updated patch as https://github.com/trofi/nix-guix-gentoo/commit/71632e84bfc334fed48a0750a0a696468a5accdc.
