### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by xorrvin** [trofi/nix-guix-gentoo#53]
Hi,

Thanks for this repo! I've tested it on rpi4 and it works, if following packages are adjusted for `~arm64`:

```
app-text/lowdown-nix
dev-cpp/rapidcheck
sys-apps/busybox-nix-sandbox-shell
sys-apps/nix
```

**Comment by trofi** [comment]
Thank you for the test! It looks like we need at least one extra dep in `::gentoo` to satisfy the depends:
- `dev-libs/editline`: https://packages.gentoo.org/packages/dev-libs/editline (only `x86 amd64` for now)

If you can request keywording on https://bugs.gentoo.org I can keyword `nix` for `~arm64` in the overlay to have the dependencies satisfied.

**Comment by trofi** [comment]
Looks like `::getntoo` got `editline` keyworded. Keyworded `nix` in `::nix-guix` as https://github.com/trofi/nix-guix-gentoo/commit/8e724e1c098d56fe9ea6ae7f167d7629b0fb0862:

```
      app-text/lowdown-nix: keywords for ~arm64 (sys-apps/nix dependency)
      dev-cpp/rapidcheck: keywords for ~arm64 (sys-apps/nix dependency)
      sys-apps/busybox-nix-sandbox-shell: keywords for ~arm64 (sys-apps/nix dependency)
      app-text/mdbook-linkcheck: keywords for ~arm64 (sys-apps/nix dependency)
      sys-apps/nix: keywords for ~arm64
```

Thank you for the test and the report!
