### ISSUE TITLE
lix fails on a fresh system installation.

### ISSUE THREAD

**Issue by mainrs** [trofi/nix-guix-gentoo#56]
Just bootstrapped my stage3 and tried to emerge lix. The installation procedure relies on `lsof`, which isn't available. I installed it via `emerge --ask --oneshot sys-process/lsof` and the emerge of `lix` worked afterwards.

Would be a good idea to add it to `DEPEND`, I think.

**Comment by trofi** [comment]
Great point! Thank you for the report and analysis! Pushed the fix as https://github.com/trofi/nix-guix-gentoo/commit/6c9e24e22db49b287aaeb01c3ad7199452a98ff2
